default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stockerize_development

test:
  <<: *default
  database: _test

production:
  database: stockerize_prod
  <<: *default
